### ISSUE TITLE
spsa_with_random_spatial attack not showing any progress

### ISSUE THREAD

**Issue by sibyjackgrove** [google/unrestricted-adversarial-examples#56]
I was able to get results from `clean`, `spatial_grid ` (1 hr 18 mintue) and, `common_corruptions` (16 minutes). But the `spsa_with_random_spatial` seems to be stuck and not showing any progress in number of iterations even ater waiting for 15 minutes. Is this normal or could this be a bug? I am using a Google Colab instance with GPU acceleration.

![image](https://user-images.githubusercontent.com/25213730/47112405-d720c880-d21b-11e8-8112-12da59471852.png)

**Comment by nottombrown** [comment]
Hmm did this end up making progress after you waited longer? If not then
can you tell me what cleverhans version you are using?

`pip freeze | grep cleverhans`

**Comment by sibyjackgrove** [comment]
Not it didn't make progress. In fact, it made the whole notebook hang and I had to restart the runtime. It seems I am using `clerverhans 2.1.0`.

![image](https://user-images.githubusercontent.com/25213730/47166497-f2461380-d2c1-11e8-970d-ec283f4845d1.png)

**Comment by nottombrown** [comment]
Investigating now. It could be that the colab kernel ran out of memory and the runtime had to restart?

I think that running the full evaluation on colab is unlikely to work, because it takes ~12 hours on a single P100 GPU. This seems like it's probably not colab's use-case.

I would recommend investigating the [deep learning images for google cloud](https://blog.kovalevskyi.com/deep-learning-images-for-google-cloud-engine-the-definitive-guide-bc74f5fb02bc)
